version: "3"
services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile_streamlit
    image: 815284215296.dkr.ecr.ap-northeast-1.amazonaws.com/automl_playground@sha256:1081938e443a1870b26c705bad6470cf97614643e722009ceddfb97a911eb287
    ports:
      - "8501:8501"
      - "8050:8050"
      - "54321:54321"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    # volumes:
    #   - ./mlruns:/app/mlruns
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile_mlflow
    image: 815284215296.dkr.ecr.ap-northeast-1.amazonaws.com/automl_playground:latest
    ports:
      - "5000:5000"
    command: mlflow server --backend-store-uri mlruns --default-artifact-root mlruns --host 0.0.0.0 --port 5000
    # volumes:
    #   - ./mlruns:/app/mlruns